# config/model/mnist_cnn.yaml
_target_: corrupted_mnist.model.MyAwesomeModel
conv1_out_channels: 32
conv2_out_channels: 64
conv3_out_channels: 128
dropout_rate: 0.5
fc1_out_features: 10
input_channels: 1