name: DVC Workflow

on:
  push:
    branches:
      - main
    paths:
      - '**/*.dvc'
      - '.dvc/**'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.dvc'
      - '.dvc/**'

jobs:
  run_data_checker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Debug directory structure
      run: |
        echo "Current directory:"
        pwd
        echo "Directory contents:"
        ls -la
        if [ -d "src" ]; then
          echo "Source directory contents:"
          ls -la src/
          if [ -d "src/corrupted_mnist" ]; then
            echo "Corrupted MNIST directory contents:"
            ls -la src/corrupted_mnist/
          else
            echo "Error: src/corrupted_mnist directory not found"
            exit 1
          fi
        else
          echo "Error: src directory not found"
          exit 1
        fi

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        cache: 'pip'
        cache-dependency-path: setup.py

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip list

    - name: Auth with GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Verify GCP Auth
      run: |
        gcloud auth list
        gcloud config list project

    - name: DVC Setup
      run: |
        echo "DVC Status:"
        dvc status || echo "DVC status failed"
        echo "DVC Remotes:"
        dvc remote list || echo "No DVC remotes configured"

    - name: Pull data
      run: |
        dvc pull --no-run-cache -v || {
          echo "DVC pull failed. Checking remote configuration..."
          dvc remote list
          exit 1
        }

    - name: Verify dataset_stat.py exists
      run: |
        if [ ! -f "src/corrupted_mnist/dataset_stat.py" ]; then
          echo "Error: dataset_stat.py not found at src/corrupted_mnist/dataset_stat.py"
          echo "Current directory structure:"
          ls -R
          exit 1
        fi

    - name: Check data statistics & generate report
      run: |
        python src/corrupted_mnist/dataset_stat.py > report.md
        if [ -f "mnist_images.png" ]; then
          echo '![](./mnist_images.png "MNIST images")' >> report.md
        fi
        if [ -f "train_label_distribution.png" ]; then
          echo '![](./train_label_distribution.png "Train label distribution")' >> report.md
        fi
        if [ -f "test_label_distribution.png" ]; then
          echo '![](./test_label_distribution.png "Test label distribution")' >> report.md
        fi

    - name: Setup CML
      uses: iterative/setup-cml@v3

    - name: Comment on PR
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cml comment create report.md --watermark-title="Data Checker"